set flipStates(lastVisitedHexDir) {}
set flipStates(lastVisitedLogDir) {}
set flipStates(recentHexFilesList) {}
set flipStates(startAppliAfterProg) 0
set flipStates(resetAfterProg) 0
set flipStates(checkSignature) 0
set flipStates(enableAutoIsp) 0
set flipStates(rstActiveHi) 1
set flipStates(psenActiveLo) 1
